export const manufacturers = [
  "Toyota",
  "Ford",
  "Volkswagen",
  "Honda",
  "General Motors",
  "BMW",
  "Mercedes-Benz",
  "Nissan",
  "Hyundai",
  "Kia",
  "Subaru",
  "Audi",
  "Tesla",
  "Volvo",
  "Jaguar",
  "Land Rover",
  "Porsche",
  "Mazda",
  "Mitsubishi",
  "Fiat",
  "Chrysler",
  "Dodge",
  "Jeep",
  "Ram",
  "Mini",
  "Lexus",
  "Acura",
  "Infiniti",
  "Alfa Romeo",
  "Maserati",
  "Aston Martin",
  "Bentley",
  "Bugatti",
  "Rolls-Royce",
  "McLaren",
  "Lotus",
  "Ferrari",
  "Lamborghini",
  "Pagani",
  "Koenigsegg",
  "Genesis",
  "Rivian",
  "Lucid Motors",
  "Karma Automotive",
  "Polestar",
  "Byton",
  "Faraday Future",
  "Rimac",
  "NIO",
  "Fisker",
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it functions", url: "/" },
      { title: "Highlighted", url: "/" },
      { title: "Collaboration", url: "/" },
      { title: "Business Relationship", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Occurrences", url: "/" },
      { title: "Weblog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Recommend a colleague", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Community", url: "/" },
      { title: "PhotoGram", url: "/" },
      { title: "Tweets", url: "/" },
      { title: "Social Network", url: "/" },
    ],
  },
];
